apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding-{{ .Release.Name }}-{{ .Chart.Name }}
subjects:
- kind: ServiceAccount
  name: svc-account-{{ .Release.Name }}-{{ .Chart.Name }}
  apiGroup: {{ .Values.roleBinding.subjects.apiGroup }}
roleRef:
  kind: Role 
  name: role-{{ .Release.Name }}-{{ .Chart.Name }}
  apiGroup: {{ .Values.roleBinding.roleRef.apiGroup }} 
