environments:
  dev:
---
# charts 
repositories:
  - name: kedacore
    url: https://kedacore.github.io/charts
  - name: rabbitmq-cluster-operator
    url: https://charts.bitnami.com/bitnami

# charts
releases:
  - name: keda
    namespace: pruebas
    chart: kedacore/keda
  - name: ingress-controller
    chart: ./charts/ingress-nginx
    namespace: ingress-nginx
  - name: rabbitmq-cluster-operator
    namespace: pruebas
    chart: bitnami/rabbitmq-cluster-operator
  - name: consumidor
    namespace: pruebas
    chart: ./charts/cons-keda
    needs: 
    - keda
    values:
      - ./envs/{{.Environment.Name}}/cons-keda.yaml
  - name: api
    namespace: pruebas
    chart: ./charts/api-cola
    values:
      - ./envs/{{.Environment.Name}}/api-cola.yaml
  - name: locust
    namespace: pruebas
    chart: ./charts/locust
    values:
      - ./envs/{{.Environment.Name}}/locust.yaml
  - name: dashboard
    namespace: pruebas
    chart: ./charts/dash-cola
    values:
      - ./envs/{{.Environment.Name}}/dash-cola.yaml
  - name: cola-pruebas
    namespace: pruebas
    chart: ./charts/rabbit
    needs: 
    - rabbitmq-cluster-operator
    values:
      - ./envs/{{.Environment.Name}}/rabbit.yaml
