FROM node:21-alpine as builder

WORKDIR /library

ADD . . 

RUN npm install 

RUN npm run build

FROM nginx:stable-alpine

RUN apk update

RUN apk add tree

COPY ./config/nginx.conf /etc/nginx/nginx.conf

COPY ./config/default.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /library/dist/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
