apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ .Release.Name }}-{{ .Chart.Name }}
spec:
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-{{ .Chart.Name }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: {{ .Values.hpa.metrics.type}}
    resource:
      {{- toYaml .Values.hpa.resource | nindent 6 }}
  behavior:
    scaleDown:
      {{- toYaml .Values.hpa.scaleDown | nindent 6 }}
    scaleUp:
      {{- toYaml .Values.hpa.scaleUp | nindent 6 }}

